image: node:latest

variables:
  S3_BUCKET_NAME: alex-s-test-bucket

stages:
  - test
  - deploy

cache:
  paths:
    - node_modules/ # This caches the dependencies between runs, saving time

checks-job:
  script:
    - npm install
    - npm run check

deploy-job:
  stage: deploy
  environment: production
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  script:
    - echo "Deploying application..."
    - aws s3 sync . s3://$S3_BUCKET_NAME/ --exclude "*" --include "*.html" --delete
    - echo "Application successfully deployed."